Create 2017-09-03-variables-in-inspector.md
duality-community/duality-community.github.io pull request #5
Opened 2017-09-03 14:53 UTC by Kliktrix

Added a post on setting variables in the inspector.

2017-09-03 17:17 UTC, mfep requested changes
Thanks for the article! Good to see stuff already happening to the repo. I've added some comments to consider, but obviously I'm open to debate.

2017-09-03 17:17 UTC, mfep commented on _posts/2017-09-03-variables-in-inspector.md
> +inspector. In Unity, you would declare the variable as public or put `[SerializeField]` in front of the variable. However, both approaches
If we mention serializing, why don't we explain Duality's `[DontSerialize]` attribute?

2017-09-03 17:17 UTC, mfep commented on _posts/2017-09-03-variables-in-inspector.md
> +work with any variable type, including integers, strings and booleans.
I might add here, that any non-builtin types can be exposed too. (I know that logically "any variable type" covers these, but it's a bit more straightforward. Or we can omit the "including" part.)

2017-09-03 17:17 UTC, mfep commented on _posts/2017-09-03-variables-in-inspector.md
> +public class EpicScript : Component
Naming variables 'epic' has quite low humor content, but renders the whole article a bit immature. I think we should call stuff something boring, like `Foo` or `MyComponent`.

2017-09-03 17:17 UTC, mfep commented on _posts/2017-09-03-variables-in-inspector.md
> +This code tells the inspector to allow the user to modify/read the variable through the inspector and then gets the value set in the
The closing sentence is somewhat convoluted. Wouldn't it be simpler if we just stated that the `get` and `set` methods are called when we modify the value in the inspector?

2017-09-03 18:06 UTC, Kliktrix commented
@mfep Thanks for the feedback. This is my first ever github project I've contributed to, so sorry for the amateur quality. I shall get right to work!

2017-09-04 08:13 UTC, Kliktrix commented
@mfep Have added all suggested changes. Please review.

2017-09-05 17:38 UTC, mfep commented
Since my last comment, I kind of changed my mind, and I think we should write an entire 'Tip' about serialization. So let's omit that part for now. Other than that, I'd merge this, thanks for the PR!

2017-09-22 10:22 UTC, mfep approved these changes

2017-09-22 10:23 UTC, mfep commented
Since, there's been no activity here for a while, I'm merging this, and do the little change requested.

2017-09-22 10:23 UTC, merged